### ISSUE TITLE
Do not download if wget::fetch { redownload => false }

### ISSUE THREAD

**Issue by jinxxik** [maestrodev/puppet-wget#26]
Add option to not download if some other condition is true..
for example downloaded file is zip (or zip of zip) which contains directory which if is unzipped fetching it again from internet is nonsense.

Add possibility to force download/ not download by redownload variable or another? variable from other test than destination exists.

Is it reasonable for you?

Thanks

**Comment by carlossg** [comment]
should be working now using the parameter source_hash

**Comment by c33s** [comment]
if i take the topic of this issue `source_hash` doesn't fix the problem. for using `source_hash` i have to know the md5 hash (which means i have to get it manually one time). 
in my case i want to download the blocklist `https://lists.blocklist.de/lists/all.txt` one time if it does not exist. after that i would update it via cron. the first call to `wget` only ensures that the file is there and the blocklist is not empty.
this means compared to `exec` that a `creates` parameter would be awesome see https://docs.puppet.com/puppet/latest/reference/type.html#exec-attribute-creates

**Comment by c33s** [comment]
found a solution, just commenting here if someone else stumble upon this issue, `unless` is the magic key. 
```
wget::fetch { $url:
  destination => $file,
  unless      => "test -f ${file}"
}
```
